- id: doi:10.1093/g3journal/jkaf052
  image: images/papers/2025_gupta.jpg

- id: doi:10.1093/oons/kvac019
  image: images/papers/2023_burton.png
  
- id: doi:10.1093/oons/kvac018
  image: images/papers/2022_burton.jpg

- id: pubmed:37668910
  image: images/papers/2024_bhandiwad.jpg

- id: doi:10.1126/sciadv.abo0549
  image: images/papers/2022_bhandiwad.jpg

- id: doi:10.1038/s41467-020-14965-y
  image: images/papers/2020_horstick.jpg

- id: pmc:PMC6793939
  image: images/papers/2019_marquart.jpg

- id: pmc:PMC6392497
  image: images/papers/2019_tabor.jpg

- id: pmc:PMC6296225
  image: images/papers/2018_gupta.jpg

- id: doi:10.1016/j.cub.2018.06.020
  image: images/papers/2018_tabor.jpg

